djangoApp/blog/urls.py
from django.urls import path, re_path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('recent/', views.recent, name='recent'),
    path('post/', views.post, name='post'),
    re_path(r'^delete/(?P<id>[0-9]+)/$', views.delete, name='delete'),
    re_path(r'^update/(?P<id>[0-9]+)/$', views.update, name='update'),

]

djangoApp/djangoApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from hello.views import index
from blog.views import articles


urlpatterns = [
    path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls', namespace='hello')),

    re_path(r'^articles/(?P<year>[0-9]{4})/$', articles, name="dinamis"),
]

djangoApp/hello/urls.py
from django.urls import path

from . import views

app_name = 'hello'
urlpatterns = [
    path('', views.index, name='index'),
]

djangoApp/blog/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    body = models.TextField()
    slug = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(self.title)
        super(Post, self).save()

    def __str__(self):
        return "{}".format(self.title)

djangoApp/hello/models.py
from django.db import models

# Create your models here.
class Data(models.Model):
    nama = models.CharField(max_length=255)
    alamat = models.TextField()

djangoApp/hello/forms.py
from django import forms


class classform(forms.Form):
    namac = forms.CharField()
    alamatc = forms.CharField()

djangoApp/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import Post
from . import formsArticle

def index(request):
    
    return render(request, 'blog/index.html')

def post(request):
    classform = formsArticle.classform(request.POST or None)

    if request.method == 'POST':
        if classform.is_valid():
            classform.save()
            return HttpResponseRedirect('/blog/post')

    db = Post.objects.all()
    context = {
        'title':'Blog',
        'heading':'Add Article Here',
        'subheading':'Posts',
        'classform': classform,
        'post': db,
    }
    return render(request, 'blog/post.html', context)

def delete(request, id):
    Post.objects.filter(id=id).delete()
    return HttpResponseRedirect('/blog/post')

def update(request, id):
    updateCurrentArt = Post.objects.get(id=id)

    data = {
        'title': updateCurrentArt.title,
        'body': updateCurrentArt.body
    }

    classform = formsArticle.classform(request.POST or None, initial=data, instance=updateCurrentArt)

    if request.method == 'POST':
        if classform.is_valid():
            classform.save()
            return HttpResponseRedirect('/blog/post')

    context = {
        'heading':'Update Article',
        'classform': classform,      
    }

    return render(request, 'blog/post.html', context)

def recent(request):
    return HttpResponse("Hello Daffa!")

def articles(request,year):
    year=year

    str = year

    return HttpResponse(year)

djangoApp/hello/views.py
from django.shortcuts import render
from . import forms

def index(request):
    classform = forms.classform()

    context = {
        'heading':'Home',
        'classform': classform
    }
    if request.method == 'POST':
      
        print("Ini adalah method POST")
        context = {
            'nama': request.POST['nama'], 
            'alamat': request.POST['alamat'],
            'namac': request.POST['namac'], 
            'alamatc': request.POST['alamatc'],
        }
    else:
        print("Ini adalah method GET")
    return render(request, 'hello/index.html', context)


       

djangoApp/blog/templates/blog/components/footer.html
<footer
  class="navbar navbar-expand-lg bg-light justify-content-center shadow-lg p-3 bg-body rounded position-sticky"
>
  &copy;
  <a
    class="text-decoration-none fs-4 text-black font-monospace fw-semibold"
    href="#"
    >2022 Daffa Ulhaq</a
  >
</footer>

djangoApp/blog/templates/blog/components/nav.html
<nav
  class="navbar navbar-expand-lg bg-light shadow-sm p-3 mb-5 bg-body rounded fixed-top"
>
  <div class="container-fluid">
    {% block navbar-brand %}
    <a class="navbar-brand" href="#"> Blog App </a>
    {% endblock navbar-brand %}
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post' %}">Articles</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'hello:index' %}">Hello App</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

djangoApp/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% load static %}
    <link
      rel="stylesheet"
      href="{% static 'css/django.css' %}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'blog/blog.css' %}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'vendor/bootstrap/css/bootstrap.css' %}"
      type="text/css"
    />

    <title>Blog App</title>
  </head>
  <body>
    {% include "blog/components/nav.html" %}
    <div class="container">
      {% block header %}
      <section id="first">
        <h1 class="first-head">
          This is Blog App by 1204045_Muhammad Rifqi Daffa Ulhaq
        </h1>
        <a href="#second" class="btn btn-outline-primary btn-lg">Scroll</a>
      </section>
      {% endblock header %}

      <section id="second">
        <h1 class="second-head">I'am Junior Developer</h1>
        <a href="#third" class="btn btn-outline-warning btn-lg">Scroll</a>
      </section>

      <!-- <section id="blog">
        {% block content-1 %}  {% endblock content-1 %}
      </section> -->

      <section id="third">
        <h2>Django was created in the fall of 2003</h2>
        <a href="#fourth" class="btn btn-outline-danger btn-lg">Scroll</a>
      </section>

      <section id="fourth">
        <h3>Spirit of learning Django</h3>
        <a href="#fifth" class="btn btn-outline-success btn-lg">Scroll</a>
      </section>

      <section id="fifth">
        <a class="link" href="https://www.djangoproject.com/">Learn django</a>
        <div>
          <a href="#sixth" class="btn btn-outline-dark btn-md">Scroll</a>
        </div>
      </section>

      <section id="sixth">
        <h1>This picture from django</h1>
        <img src="{% static 'blog/img/code.jpg' %}" alt="" />
        <a href="#first" class="btn btn-outline-info btn-lg mt-3">Up</a>
      </section>
    </div>
    {% include "blog/components/footer.html" %}

    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

djangoApp/blog/templates/blog/post.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Articles</title>
    {% load static %}
    <link
      rel="stylesheet"
      href="{% static 'vendor/bootstrap/css/bootstrap.css' %}"
      type="text/css"
    />
  </head>
  <body>
    <div class="container mt-2">
      <a class="btn btn-secondary" href="{% url 'blog:index' %}">Home</a>
      <div class="row mt-2">
        <div class="col-md-6 mx-auto">
          <div class="card shadow rounded">
            <div class="card-body">
              <form method="post">
                {% csrf_token %}
                <h2>Article</h2>
                <table class="table">
                  {{classform.as_table}}
                </table>
                <button type="submit" class="btn btn-primary w-100">
                  Submit
                </button>
              </form>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Title</th>
                <th>Body</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for v in post %}
              <tr>
                <td>{{v.title}}</td>
                <td>{{v.body}}</td>
                <td>
                  <a
                    class="btn btn-sm btn-danger"
                    href="{% url 'blog:delete' v.id %}"
                    >Delete</a
                  >
                </td>
                <td>
                  <a
                    class="btn btn-sm btn-info"
                    href="{% url 'blog:update' v.id %}"
                    >Update</a
                  >
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </body>
</html>

djangoApp/hello/templates/hello/index.html
{% extends "blog/index.html" %} {% block header %}
<section>
  <form method="post">
    {% csrf_token %}
    <h2>Form Django</h2>
    <table class="table">
      {{classform.as_table}}
    </table>
    <h2>Form HTML</h2>
    <label class="form-label" for="nama">Nama</label>
    <input type="text" class="form-control" name="nama" id="nama" />

    <br />

    <label class="form-label" for="alamat">Alamat</label>
    <input type="text" class="form-control" name="alamat" id="alamat" />

    <br />

    <button type="submit" class="btn btn-primary w-100">Submit</button>
  </form>

  <h2>{{nama}} {{namac}}</h2>
  <h2>{{alamat}} {{alamatc}}</h2>
</section>

{% endblock header %}